name: Deploy Frontend To Azure Static Web Apps (Prod)

on:
  push:
    branches:
      - prod
    paths:
      - "frontend/**"
      - ".github/workflows/azure-static-web-apps-prod.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Prod Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy To Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "frontend"
          skip_app_build: true
          output_location: ""
